name: Build and pack JSX

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build binaries
      run: cargo build --release

    - uses: actions/setup-node@v4
      with:
        node-version: 21

    - name: NPM Build
      run: |
        npm install
        npm run build
        npm run pack

    - name: Upload package to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets
        asset_path: ./dist/jsx-1.0.0.tgz
        asset_name: jsx-1.0.0.tgz
        asset_content_type: application/gzip
